// src/lib/import/municipality-lookup.ts
// Phase 7b (T5b): Maps every Finnish kuntanumero to municipality name,
// Luke price region, and growth multiplier.
//
// Generated from Tilastokeskus kuntaluettelo + Luke region mapping.
// Update: re-run scripts/generate-kuntanumero-map.ts after municipality mergers.

export interface MunicipalityInfo {
  name: string;
  priceRegion: string;
  growthMultiplier: number;
}

export const KUNTANUMERO_MAP: Record<string, MunicipalityInfo> = {
  // ── Uusimaa (01) — region 1, multiplier 1.10 ──
  "005": { name: "Alajärvi", priceRegion: "6", growthMultiplier: 1.00 },
  "009": { name: "Alavieska", priceRegion: "71", growthMultiplier: 0.80 },
  "010": { name: "Alavus", priceRegion: "6", growthMultiplier: 1.00 },
  "016": { name: "Asikkala", priceRegion: "1", growthMultiplier: 1.10 },
  "018": { name: "Askola", priceRegion: "1", growthMultiplier: 1.10 },
  "019": { name: "Aura", priceRegion: "1", growthMultiplier: 1.10 },
  "020": { name: "Brändö", priceRegion: "1", growthMultiplier: 1.10 },
  "035": { name: "Eckerö", priceRegion: "1", growthMultiplier: 1.10 },
  "043": { name: "Enonkoski", priceRegion: "4", growthMultiplier: 0.90 },
  "046": { name: "Enontekiö", priceRegion: "8", growthMultiplier: 0.55 },
  "047": { name: "Espoo", priceRegion: "1", growthMultiplier: 1.10 },
  "049": { name: "Eura", priceRegion: "1", growthMultiplier: 1.10 },
  "050": { name: "Eurajoki", priceRegion: "1", growthMultiplier: 1.10 },
  "051": { name: "Evijärvi", priceRegion: "6", growthMultiplier: 1.00 },
  "060": { name: "Finström", priceRegion: "1", growthMultiplier: 1.10 },
  "061": { name: "Forssa", priceRegion: "1", growthMultiplier: 1.10 },
  "062": { name: "Föglö", priceRegion: "1", growthMultiplier: 1.10 },
  "065": { name: "Geta", priceRegion: "1", growthMultiplier: 1.10 },
  "069": { name: "Haapajärvi", priceRegion: "71", growthMultiplier: 0.80 },
  "071": { name: "Haapavesi", priceRegion: "71", growthMultiplier: 0.80 },
  "072": { name: "Hailuoto", priceRegion: "71", growthMultiplier: 0.80 },
  "074": { name: "Halsua", priceRegion: "71", growthMultiplier: 0.80 },
  "075": { name: "Hamina", priceRegion: "5", growthMultiplier: 1.05 },
  "076": { name: "Hammarland", priceRegion: "1", growthMultiplier: 1.10 },
  "077": { name: "Hankasalmi", priceRegion: "3", growthMultiplier: 1.00 },
  "078": { name: "Hanko", priceRegion: "1", growthMultiplier: 1.10 },
  "079": { name: "Harjavalta", priceRegion: "1", growthMultiplier: 1.10 },
  "081": { name: "Hartola", priceRegion: "1", growthMultiplier: 1.10 },
  "082": { name: "Hattula", priceRegion: "1", growthMultiplier: 1.10 },
  "086": { name: "Hausjärvi", priceRegion: "1", growthMultiplier: 1.10 },
  "090": { name: "Heinävesi", priceRegion: "4", growthMultiplier: 0.90 },
  "091": { name: "Helsinki", priceRegion: "1", growthMultiplier: 1.10 },
  "092": { name: "Hirvensalmi", priceRegion: "4", growthMultiplier: 0.90 },
  "097": { name: "Hollola", priceRegion: "1", growthMultiplier: 1.10 },
  "098": { name: "Honkajoki", priceRegion: "1", growthMultiplier: 1.10 },
  "099": { name: "Humppila", priceRegion: "1", growthMultiplier: 1.10 },
  "102": { name: "Huittinen", priceRegion: "1", growthMultiplier: 1.10 },
  "103": { name: "Hyrynsalmi", priceRegion: "72", growthMultiplier: 0.75 },
  "105": { name: "Hyvinkää", priceRegion: "1", growthMultiplier: 1.10 },
  "106": { name: "Hämeenkyrö", priceRegion: "1", growthMultiplier: 1.10 },
  "108": { name: "Hämeenlinna", priceRegion: "1", growthMultiplier: 1.10 },
  "109": { name: "Ii", priceRegion: "71", growthMultiplier: 0.80 },
  "111": { name: "Iisalmi", priceRegion: "4", growthMultiplier: 0.90 },
  "139": { name: "Iitti", priceRegion: "5", growthMultiplier: 1.05 },
  "140": { name: "Ikaalinen", priceRegion: "1", growthMultiplier: 1.10 },
  "142": { name: "Ilmajoki", priceRegion: "6", growthMultiplier: 1.00 },
  "143": { name: "Ilomantsi", priceRegion: "4", growthMultiplier: 0.90 },
  "145": { name: "Imatra", priceRegion: "5", growthMultiplier: 1.05 },
  "146": { name: "Inari", priceRegion: "8", growthMultiplier: 0.55 },
  "148": { name: "Inkoo", priceRegion: "1", growthMultiplier: 1.10 },
  "149": { name: "Isojoki", priceRegion: "6", growthMultiplier: 1.00 },
  "151": { name: "Isokyrö", priceRegion: "6", growthMultiplier: 1.00 },
  "152": { name: "Isokyrö", priceRegion: "6", growthMultiplier: 1.00 },
  "153": { name: "Janakkala", priceRegion: "1", growthMultiplier: 1.10 },
  "165": { name: "Joensuu", priceRegion: "4", growthMultiplier: 0.90 },
  "167": { name: "Jokioinen", priceRegion: "1", growthMultiplier: 1.10 },
  "169": { name: "Jomala", priceRegion: "1", growthMultiplier: 1.10 },
  "170": { name: "Joroinen", priceRegion: "4", growthMultiplier: 0.90 },
  "171": { name: "Joutsa", priceRegion: "3", growthMultiplier: 1.00 },
  "172": { name: "Juankoski", priceRegion: "4", growthMultiplier: 0.90 },
  "176": { name: "Juuka", priceRegion: "4", growthMultiplier: 0.90 },
  "177": { name: "Juupajoki", priceRegion: "1", growthMultiplier: 1.10 },
  "178": { name: "Juva", priceRegion: "4", growthMultiplier: 0.90 },
  "179": { name: "Jyväskylä", priceRegion: "3", growthMultiplier: 1.00 },
  "181": { name: "Jämijärvi", priceRegion: "1", growthMultiplier: 1.10 },
  "182": { name: "Jämsä", priceRegion: "3", growthMultiplier: 1.00 },
  "186": { name: "Järvenpää", priceRegion: "1", growthMultiplier: 1.10 },
  "202": { name: "Kaarina", priceRegion: "1", growthMultiplier: 1.10 },
  "204": { name: "Kaavi", priceRegion: "4", growthMultiplier: 0.90 },
  "205": { name: "Kajaani", priceRegion: "72", growthMultiplier: 0.75 },
  "208": { name: "Kalajoki", priceRegion: "71", growthMultiplier: 0.80 },
  "211": { name: "Kangasala", priceRegion: "1", growthMultiplier: 1.10 },
  "213": { name: "Kangasniemi", priceRegion: "4", growthMultiplier: 0.90 },
  "214": { name: "Kankaanpää", priceRegion: "1", growthMultiplier: 1.10 },
  "216": { name: "Kannonkoski", priceRegion: "3", growthMultiplier: 1.00 },
  "217": { name: "Kannus", priceRegion: "71", growthMultiplier: 0.80 },
  "218": { name: "Karijoki", priceRegion: "6", growthMultiplier: 1.00 },
  "224": { name: "Karkkila", priceRegion: "1", growthMultiplier: 1.10 },
  "226": { name: "Karstula", priceRegion: "3", growthMultiplier: 1.00 },
  "230": { name: "Karvia", priceRegion: "1", growthMultiplier: 1.10 },
  "231": { name: "Kaskinen", priceRegion: "6", growthMultiplier: 1.00 },
  "232": { name: "Kauhajoki", priceRegion: "6", growthMultiplier: 1.00 },
  "233": { name: "Kauhava", priceRegion: "6", growthMultiplier: 1.00 },
  "235": { name: "Kauniainen", priceRegion: "1", growthMultiplier: 1.10 },
  "236": { name: "Kaustinen", priceRegion: "71", growthMultiplier: 0.80 },
  "239": { name: "Keitele", priceRegion: "4", growthMultiplier: 0.90 },
  "240": { name: "Kemi", priceRegion: "8", growthMultiplier: 0.55 },
  "241": { name: "Kemijärvi", priceRegion: "8", growthMultiplier: 0.55 },
  "244": { name: "Keminmaa", priceRegion: "8", growthMultiplier: 0.55 },
  "245": { name: "Kempele", priceRegion: "71", growthMultiplier: 0.80 },
  "249": { name: "Kerava", priceRegion: "1", growthMultiplier: 1.10 },
  "250": { name: "Keuruu", priceRegion: "3", growthMultiplier: 1.00 },
  "256": { name: "Kihniö", priceRegion: "1", growthMultiplier: 1.10 },
  "257": { name: "Kinnula", priceRegion: "3", growthMultiplier: 1.00 },
  "260": { name: "Kirkkonummi", priceRegion: "1", growthMultiplier: 1.10 },
  "261": { name: "Kitee", priceRegion: "4", growthMultiplier: 0.90 },
  "263": { name: "Kittilä", priceRegion: "8", growthMultiplier: 0.55 },
  "265": { name: "Kiuruvesi", priceRegion: "4", growthMultiplier: 0.90 },
  "271": { name: "Kivijärvi", priceRegion: "3", growthMultiplier: 1.00 },
  "272": { name: "Kokkola", priceRegion: "71", growthMultiplier: 0.80 },
  "273": { name: "Kolari", priceRegion: "8", growthMultiplier: 0.55 },
  "275": { name: "Konnevesi", priceRegion: "3", growthMultiplier: 1.00 },
  "276": { name: "Kontiolahti", priceRegion: "4", growthMultiplier: 0.90 },
  "280": { name: "Korsnäs", priceRegion: "6", growthMultiplier: 1.00 },
  "284": { name: "Koski Tl", priceRegion: "1", growthMultiplier: 1.10 },
  "285": { name: "Kotka", priceRegion: "5", growthMultiplier: 1.05 },
  "286": { name: "Kouvola", priceRegion: "5", growthMultiplier: 1.05 },
  "287": { name: "Kristiinankaupunki", priceRegion: "6", growthMultiplier: 1.00 },
  "288": { name: "Kruunupyy", priceRegion: "71", growthMultiplier: 0.80 },
  "290": { name: "Kuhmo", priceRegion: "72", growthMultiplier: 0.75 },
  "291": { name: "Kuhmoinen", priceRegion: "3", growthMultiplier: 1.00 },
  "295": { name: "Kumlinge", priceRegion: "1", growthMultiplier: 1.10 },
  "297": { name: "Kuopio", priceRegion: "4", growthMultiplier: 0.90 },
  "300": { name: "Kuortane", priceRegion: "6", growthMultiplier: 1.00 },
  "301": { name: "Kurikka", priceRegion: "6", growthMultiplier: 1.00 },
  "304": { name: "Kustavi", priceRegion: "1", growthMultiplier: 1.10 },
  "305": { name: "Kuusamo", priceRegion: "72", growthMultiplier: 0.75 },
  "309": { name: "Kyyjärvi", priceRegion: "3", growthMultiplier: 1.00 },
  "312": { name: "Kärkölä", priceRegion: "1", growthMultiplier: 1.10 },
  "316": { name: "Kärsämäki", priceRegion: "71", growthMultiplier: 0.80 },
  "317": { name: "Kökar", priceRegion: "1", growthMultiplier: 1.10 },
  "318": { name: "Köyliö", priceRegion: "1", growthMultiplier: 1.10 },
  "320": { name: "Lahti", priceRegion: "1", growthMultiplier: 1.10 },
  "322": { name: "Laihia", priceRegion: "6", growthMultiplier: 1.00 },
  "398": { name: "Laitila", priceRegion: "1", growthMultiplier: 1.10 },
  "399": { name: "Lapinjärvi", priceRegion: "1", growthMultiplier: 1.10 },
  "400": { name: "Lapinlahti", priceRegion: "4", growthMultiplier: 0.90 },
  "402": { name: "Lappajärvi", priceRegion: "6", growthMultiplier: 1.00 },
  "403": { name: "Lappeenranta", priceRegion: "5", growthMultiplier: 1.05 },
  "405": { name: "Lapua", priceRegion: "6", growthMultiplier: 1.00 },
  "407": { name: "Laukaa", priceRegion: "3", growthMultiplier: 1.00 },
  "408": { name: "Lavia", priceRegion: "1", growthMultiplier: 1.10 },
  "410": { name: "Lemi", priceRegion: "5", growthMultiplier: 1.05 },
  "416": { name: "Lemland", priceRegion: "1", growthMultiplier: 1.10 },
  "417": { name: "Lempäälä", priceRegion: "1", growthMultiplier: 1.10 },
  "418": { name: "Leppävirta", priceRegion: "4", growthMultiplier: 0.90 },
  "420": { name: "Lestijärvi", priceRegion: "71", growthMultiplier: 0.80 },
  "421": { name: "Lieksa", priceRegion: "4", growthMultiplier: 0.90 },
  "422": { name: "Lieto", priceRegion: "1", growthMultiplier: 1.10 },
  "423": { name: "Liminka", priceRegion: "71", growthMultiplier: 0.80 },
  "425": { name: "Liperi", priceRegion: "4", growthMultiplier: 0.90 },
  "426": { name: "Lohja", priceRegion: "1", growthMultiplier: 1.10 },
  "430": { name: "Loimaa", priceRegion: "1", growthMultiplier: 1.10 },
  "433": { name: "Loppi", priceRegion: "1", growthMultiplier: 1.10 },
  "434": { name: "Loviisa", priceRegion: "1", growthMultiplier: 1.10 },
  "435": { name: "Luhanka", priceRegion: "3", growthMultiplier: 1.00 },
  "436": { name: "Lumijoki", priceRegion: "71", growthMultiplier: 0.80 },
  "438": { name: "Lumparland", priceRegion: "1", growthMultiplier: 1.10 },
  "440": { name: "Luumäki", priceRegion: "5", growthMultiplier: 1.05 },
  "441": { name: "Luvia", priceRegion: "1", growthMultiplier: 1.10 },
  "442": { name: "Maalahti", priceRegion: "6", growthMultiplier: 1.00 },
  "444": { name: "Maaninka", priceRegion: "4", growthMultiplier: 0.90 },
  "445": { name: "Maarianhamina", priceRegion: "1", growthMultiplier: 1.10 },
  "475": { name: "Marttila", priceRegion: "1", growthMultiplier: 1.10 },
  "476": { name: "Masku", priceRegion: "1", growthMultiplier: 1.10 },
  "478": { name: "Merijärvi", priceRegion: "71", growthMultiplier: 0.80 },
  "480": { name: "Merikarvia", priceRegion: "1", growthMultiplier: 1.10 },
  "481": { name: "Miehikkälä", priceRegion: "5", growthMultiplier: 1.05 },
  "483": { name: "Mikkeli", priceRegion: "4", growthMultiplier: 0.90 },
  "489": { name: "Muhos", priceRegion: "71", growthMultiplier: 0.80 },
  "491": { name: "Multia", priceRegion: "3", growthMultiplier: 1.00 },
  "493": { name: "Muonio", priceRegion: "8", growthMultiplier: 0.55 },
  "495": { name: "Mustasaari", priceRegion: "6", growthMultiplier: 1.00 },
  "498": { name: "Muurame", priceRegion: "3", growthMultiplier: 1.00 },
  "499": { name: "Mynämäki", priceRegion: "1", growthMultiplier: 1.10 },
  "500": { name: "Myrskylä", priceRegion: "1", growthMultiplier: 1.10 },
  "503": { name: "Mäntsälä", priceRegion: "1", growthMultiplier: 1.10 },
  "504": { name: "Mänttä-Vilppula", priceRegion: "1", growthMultiplier: 1.10 },
  "505": { name: "Mäntyharju", priceRegion: "5", growthMultiplier: 1.05 },
  "507": { name: "Naantali", priceRegion: "1", growthMultiplier: 1.10 },
  "508": { name: "Nakkila", priceRegion: "1", growthMultiplier: 1.10 },
  "529": { name: "Nivala", priceRegion: "71", growthMultiplier: 0.80 },
  "531": { name: "Nokia", priceRegion: "1", growthMultiplier: 1.10 },
  "532": { name: "Nousiainen", priceRegion: "1", growthMultiplier: 1.10 },
  "535": { name: "Nurmes", priceRegion: "4", growthMultiplier: 0.90 },
  "536": { name: "Nurmijärvi", priceRegion: "1", growthMultiplier: 1.10 },
  "538": { name: "Närpiö", priceRegion: "6", growthMultiplier: 1.00 },
  "541": { name: "Orimattila", priceRegion: "1", growthMultiplier: 1.10 },
  "543": { name: "Oripää", priceRegion: "1", growthMultiplier: 1.10 },
  "545": { name: "Orivesi", priceRegion: "1", growthMultiplier: 1.10 },
  "560": { name: "Oulainen", priceRegion: "71", growthMultiplier: 0.80 },
  "561": { name: "Oulu", priceRegion: "71", growthMultiplier: 0.80 },
  "562": { name: "Outokumpu", priceRegion: "4", growthMultiplier: 0.90 },
  "563": { name: "Padasjoki", priceRegion: "1", growthMultiplier: 1.10 },
  "576": { name: "Paimio", priceRegion: "1", growthMultiplier: 1.10 },
  "577": { name: "Paltamo", priceRegion: "72", growthMultiplier: 0.75 },
  "578": { name: "Parainen", priceRegion: "1", growthMultiplier: 1.10 },
  "580": { name: "Parikkala", priceRegion: "5", growthMultiplier: 1.05 },
  "581": { name: "Parkano", priceRegion: "1", growthMultiplier: 1.10 },
  "583": { name: "Pedersöre", priceRegion: "6", growthMultiplier: 1.00 },
  "584": { name: "Pelkosenniemi", priceRegion: "8", growthMultiplier: 0.55 },
  "588": { name: "Pello", priceRegion: "8", growthMultiplier: 0.55 },
  "592": { name: "Perho", priceRegion: "71", growthMultiplier: 0.80 },
  "593": { name: "Pertunmaa", priceRegion: "4", growthMultiplier: 0.90 },
  "595": { name: "Petäjävesi", priceRegion: "3", growthMultiplier: 1.00 },
  "598": { name: "Pieksämäki", priceRegion: "4", growthMultiplier: 0.90 },
  "599": { name: "Pielavesi", priceRegion: "4", growthMultiplier: 0.90 },
  "601": { name: "Pietarsaari", priceRegion: "71", growthMultiplier: 0.80 },
  "604": { name: "Pihtipudas", priceRegion: "3", growthMultiplier: 1.00 },
  "607": { name: "Pirkkala", priceRegion: "1", growthMultiplier: 1.10 },
  "608": { name: "Polvijärvi", priceRegion: "4", growthMultiplier: 0.90 },
  "609": { name: "Pomarkku", priceRegion: "1", growthMultiplier: 1.10 },
  "611": { name: "Pori", priceRegion: "1", growthMultiplier: 1.10 },
  "614": { name: "Pornainen", priceRegion: "1", growthMultiplier: 1.10 },
  "615": { name: "Porvoo", priceRegion: "1", growthMultiplier: 1.10 },
  "616": { name: "Posio", priceRegion: "8", growthMultiplier: 0.55 },
  "619": { name: "Pukkila", priceRegion: "1", growthMultiplier: 1.10 },
  "620": { name: "Punkalaidun", priceRegion: "1", growthMultiplier: 1.10 },
  "623": { name: "Puolanka", priceRegion: "72", growthMultiplier: 0.75 },
  "624": { name: "Puumala", priceRegion: "4", growthMultiplier: 0.90 },
  "625": { name: "Pyhtää", priceRegion: "5", growthMultiplier: 1.05 },
  "626": { name: "Pyhäjoki", priceRegion: "71", growthMultiplier: 0.80 },
  "630": { name: "Pyhäjärvi", priceRegion: "71", growthMultiplier: 0.80 },
  "631": { name: "Pyhäntä", priceRegion: "71", growthMultiplier: 0.80 },
  "632": { name: "Pyhäranta", priceRegion: "1", growthMultiplier: 1.10 },
  "635": { name: "Pälkäne", priceRegion: "1", growthMultiplier: 1.10 },
  "636": { name: "Pöytyä", priceRegion: "1", growthMultiplier: 1.10 },
  "678": { name: "Raahe", priceRegion: "71", growthMultiplier: 0.80 },
  "680": { name: "Raisio", priceRegion: "1", growthMultiplier: 1.10 },
  "681": { name: "Rantasalmi", priceRegion: "4", growthMultiplier: 0.90 },
  "683": { name: "Ranua", priceRegion: "8", growthMultiplier: 0.55 },
  "684": { name: "Rauma", priceRegion: "1", growthMultiplier: 1.10 },
  "686": { name: "Rautalampi", priceRegion: "4", growthMultiplier: 0.90 },
  "687": { name: "Rautavaara", priceRegion: "4", growthMultiplier: 0.90 },
  "689": { name: "Rautjärvi", priceRegion: "5", growthMultiplier: 1.05 },
  "691": { name: "Reisjärvi", priceRegion: "71", growthMultiplier: 0.80 },
  "694": { name: "Riihimäki", priceRegion: "1", growthMultiplier: 1.10 },
  "697": { name: "Ristijärvi", priceRegion: "72", growthMultiplier: 0.75 },
  "698": { name: "Rovaniemi", priceRegion: "8", growthMultiplier: 0.55 },
  "700": { name: "Ruokolahti", priceRegion: "5", growthMultiplier: 1.05 },
  "702": { name: "Ruovesi", priceRegion: "1", growthMultiplier: 1.10 },
  "704": { name: "Rusko", priceRegion: "1", growthMultiplier: 1.10 },
  "707": { name: "Rääkkylä", priceRegion: "4", growthMultiplier: 0.90 },
  "710": { name: "Saarijärvi", priceRegion: "3", growthMultiplier: 1.00 },
  "729": { name: "Salla", priceRegion: "8", growthMultiplier: 0.55 },
  "732": { name: "Salo", priceRegion: "1", growthMultiplier: 1.10 },
  "734": { name: "Saltvik", priceRegion: "1", growthMultiplier: 1.10 },
  "736": { name: "Sastamala", priceRegion: "1", growthMultiplier: 1.10 },
  "738": { name: "Sauvo", priceRegion: "1", growthMultiplier: 1.10 },
  "739": { name: "Savitaipale", priceRegion: "5", growthMultiplier: 1.05 },
  "740": { name: "Savonlinna", priceRegion: "4", growthMultiplier: 0.90 },
  "742": { name: "Savukoski", priceRegion: "8", growthMultiplier: 0.55 },
  "743": { name: "Seinäjoki", priceRegion: "6", growthMultiplier: 1.00 },
  "746": { name: "Sievi", priceRegion: "71", growthMultiplier: 0.80 },
  "747": { name: "Siikainen", priceRegion: "1", growthMultiplier: 1.10 },
  "748": { name: "Siikajoki", priceRegion: "71", growthMultiplier: 0.80 },
  "749": { name: "Siikalatva", priceRegion: "71", growthMultiplier: 0.80 },
  "751": { name: "Siilinjärvi", priceRegion: "4", growthMultiplier: 0.90 },
  "753": { name: "Simo", priceRegion: "8", growthMultiplier: 0.55 },
  "755": { name: "Sipoo", priceRegion: "1", growthMultiplier: 1.10 },
  "758": { name: "Siuntio", priceRegion: "1", growthMultiplier: 1.10 },
  "759": { name: "Sodankylä", priceRegion: "8", growthMultiplier: 0.55 },
  "761": { name: "Soini", priceRegion: "6", growthMultiplier: 1.00 },
  "762": { name: "Somero", priceRegion: "1", growthMultiplier: 1.10 },
  "765": { name: "Sonkajärvi", priceRegion: "4", growthMultiplier: 0.90 },
  "766": { name: "Sotkamo", priceRegion: "72", growthMultiplier: 0.75 },
  "768": { name: "Sottunga", priceRegion: "1", growthMultiplier: 1.10 },
  "771": { name: "Sulkava", priceRegion: "4", growthMultiplier: 0.90 },
  "777": { name: "Sund", priceRegion: "1", growthMultiplier: 1.10 },
  "778": { name: "Suomussalmi", priceRegion: "72", growthMultiplier: 0.75 },
  "781": { name: "Suonenjoki", priceRegion: "4", growthMultiplier: 0.90 },
  "783": { name: "Sysmä", priceRegion: "1", growthMultiplier: 1.10 },
  "785": { name: "Säkylä", priceRegion: "1", growthMultiplier: 1.10 },
  "790": { name: "Taipalsaari", priceRegion: "5", growthMultiplier: 1.05 },
  "791": { name: "Taivalkoski", priceRegion: "72", growthMultiplier: 0.75 },
  "792": { name: "Taivassalo", priceRegion: "1", growthMultiplier: 1.10 },
  "820": { name: "Tammela", priceRegion: "1", growthMultiplier: 1.10 },
  "831": { name: "Tampere", priceRegion: "1", growthMultiplier: 1.10 },
  "833": { name: "Tervo", priceRegion: "4", growthMultiplier: 0.90 },
  "834": { name: "Tervola", priceRegion: "8", growthMultiplier: 0.55 },
  "837": { name: "Teuva", priceRegion: "6", growthMultiplier: 1.00 },
  "844": { name: "Tohmajärvi", priceRegion: "4", growthMultiplier: 0.90 },
  "845": { name: "Toholampi", priceRegion: "71", growthMultiplier: 0.80 },
  "848": { name: "Toivakka", priceRegion: "3", growthMultiplier: 1.00 },
  "849": { name: "Tornio", priceRegion: "8", growthMultiplier: 0.55 },
  "851": { name: "Turku", priceRegion: "1", growthMultiplier: 1.10 },
  "853": { name: "Tuusniemi", priceRegion: "4", growthMultiplier: 0.90 },
  "854": { name: "Tuusula", priceRegion: "1", growthMultiplier: 1.10 },
  "857": { name: "Tyrnävä", priceRegion: "71", growthMultiplier: 0.80 },
  "859": { name: "Ulvila", priceRegion: "1", growthMultiplier: 1.10 },
  "886": { name: "Urjala", priceRegion: "1", growthMultiplier: 1.10 },
  "887": { name: "Utajärvi", priceRegion: "71", growthMultiplier: 0.80 },
  "889": { name: "Utsjoki", priceRegion: "8", growthMultiplier: 0.55 },
  "890": { name: "Uurainen", priceRegion: "3", growthMultiplier: 1.00 },
  "892": { name: "Uusikaarlepyy", priceRegion: "6", growthMultiplier: 1.00 },
  "893": { name: "Uusikaupunki", priceRegion: "1", growthMultiplier: 1.10 },
  "895": { name: "Vaala", priceRegion: "72", growthMultiplier: 0.75 },
  "905": { name: "Vaasa", priceRegion: "6", growthMultiplier: 1.00 },
  "908": { name: "Valkeakoski", priceRegion: "1", growthMultiplier: 1.10 },
  "911": { name: "Valtimo", priceRegion: "4", growthMultiplier: 0.90 },
  "915": { name: "Vantaa", priceRegion: "1", growthMultiplier: 1.10 },
  "918": { name: "Varkaus", priceRegion: "4", growthMultiplier: 0.90 },
  "921": { name: "Vehmaa", priceRegion: "1", growthMultiplier: 1.10 },
  "922": { name: "Vesanto", priceRegion: "4", growthMultiplier: 0.90 },
  "924": { name: "Vesilahti", priceRegion: "1", growthMultiplier: 1.10 },
  "925": { name: "Veteli", priceRegion: "71", growthMultiplier: 0.80 },
  "927": { name: "Vieremä", priceRegion: "4", growthMultiplier: 0.90 },
  "931": { name: "Vihti", priceRegion: "1", growthMultiplier: 1.10 },
  "934": { name: "Viitasaari", priceRegion: "3", growthMultiplier: 1.00 },
  "935": { name: "Vimpeli", priceRegion: "6", growthMultiplier: 1.00 },
  "936": { name: "Virolahti", priceRegion: "5", growthMultiplier: 1.05 },
  "941": { name: "Virrat", priceRegion: "1", growthMultiplier: 1.10 },
  "946": { name: "Vårdö", priceRegion: "1", growthMultiplier: 1.10 },
  "976": { name: "Ylitornio", priceRegion: "8", growthMultiplier: 0.55 },
  "977": { name: "Ylivieska", priceRegion: "71", growthMultiplier: 0.80 },
  "980": { name: "Ylöjärvi", priceRegion: "1", growthMultiplier: 1.10 },
  "981": { name: "Ypäjä", priceRegion: "1", growthMultiplier: 1.10 },
  "989": { name: "Ähtäri", priceRegion: "6", growthMultiplier: 1.00 },
  "992": { name: "Äänekoski", priceRegion: "3", growthMultiplier: 1.00 },
};

/**
 * Look up a municipality by its 3-digit kuntanumero.
 * Returns a fallback entry if unknown.
 */
export function lookupMunicipality(kuntanumero: string): MunicipalityInfo {
  return KUNTANUMERO_MAP[kuntanumero] ?? {
    name: "Tuntematon",
    priceRegion: "9",
    growthMultiplier: 1.0,
  };
}

/**
 * Resolve municipality info from a Finnish property ID (kiinteistötunnus).
 * The first 3 digits of the normalized ID are the kuntanumero.
 *
 * Example: "989-405-0001-0405" → municipality "989" → Ähtäri, region 6, gm=1.00
 */
export function resolveMunicipalityFromPropertyId(propertyId: string): MunicipalityInfo {
  const normalized = propertyId.replace(/-/g, "");
  const kuntanumero = normalized.slice(0, 3);
  return lookupMunicipality(kuntanumero);
}
